added generate mock data and cli
htmlacademy-nodejs/654801-typoteka-3 pull request #3
Opened 2021-08-05 16:17 UTC by Alexcsmbz

2021-08-05 18:26 UTC, dean992008 requested changes

2021-08-05 18:26 UTC, dean992008 commented on .gitignore
> +mock.json
В конце всех файлов должна быть пустая строка, можно выполнить автоформатирование чтобы исправить это.

2021-08-05 18:26 UTC, dean992008 commented on src/constants.js
> +  error: 1,
В перечислениях ключи должны быть аперкейсом
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2021-08-05 18:26 UTC, dean992008 commented on src/service/cli/generate.js
> +          return console.error(`Can't write data to file... Code ${ExitCode.error}`);
В случает ошибки нужно выходить с приложения и возвращать код ошибки.

2021-08-05 18:26 UTC, dean992008 commented on src/service/cli/utils.js
> +const getRandomInt = (min, max) => Math.floor(Math.random() * (Math.floor(max) - Math.ceil(min) + 1)) + Math.ceil(min);
В большинстве стайлгайдов рекомендуется чтобы в строке кода было не более 80-100 символов, если больше такой код тяжело читать. 
В этой и следущий строке 120 и 154 символа.

2021-08-05 18:26 UTC, dean992008 commented on src/service/cli/utils.js
> +const getRandomInt = (min, max) => Math.floor(Math.random() * (Math.floor(max) - Math.ceil(min) + 1)) + Math.ceil(min);
Как по мне здесь слишком много округлений, я бы делал также как и здесь, но округлял бы только в самом конце.

2021-08-05 18:26 UTC, dean992008 commented on src/service/cli/utils.js
> +const generateAds = (count) => (
Это не утилитарная функция, а конкретная бизнес логика, поэтому я бы перенес эту функцию в `generate`

2021-08-05 18:26 UTC, dean992008 commented on src/service/cli/generate.js
> +          return console.error(`Can't write data to file... Code ${ExitCode.error}`);
Вод нужно возвращать в функцию `process.exit`

2021-08-07 16:08 UTC, dean992008 commented on src/service/cli/utils.js
> +) => dayjs(new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))).format(`YYYY-MM-DD HH:mm:ss`);
Я бы еще посоветовал отрефакторить функцию, заменив: 
```
start.getTime() + Math.random() * (end.getTime() - start.getTime()))
```
на
```
getRandomInt(start.getTime(), end.getTime())
```
Cейчас нарушает принцип `DRY`.

2021-08-07 16:10 UTC, dean992008 commented
Прийму, а новый правки по новому коментарий, сделай пожалуйста в слеудующем PR.

2021-08-07 16:10 UTC, merged

2021-08-07 16:11 UTC, Alexcsmbz commented on src/service/cli/utils.js
> +) => dayjs(new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()))).format(`YYYY-MM-DD HH:mm:ss`);
Давай оставим, как есть)